#!/bin/bash

# TODO Can't yet replace a setup like
# http://blog.ployst.com/development/2015/12/22/letsencrypt-on-kubernetes.html
# This script currently assumes a single replica of the container
#  - rarely restarted but always within 90 days.
# Multiple replicas need to share /etc/letsencrypt as volume and make sure only one at a time is renewing certs.
# We also need to bypass renew for existing certs until X days before expiry.

if [ -n "${cert_email+1}" ]; then
  sleep "$cert_delay"
fi

EMAIL=${cert_email}
DOMAINS=(${cert_domains})

if [ -z "$DOMAINS" ]; then
  echo "ERROR: Domain list is empty or unset"
  exit 1
fi

if [ -z "$EMAIL" ]; then
  echo "ERROR: Email is empty string or unset"
  exit 1
fi

if [ -n "${LETSENCRYPT_ENDPOINT+1}" ]; then
  echo "server = $LETSENCRYPT_ENDPOINT" >> /etc/letsencrypt/cli.ini
fi

for i in "${DOMAINS[@]}"
do
  if [ -d "/etc/letsencrypt/live/$i" ]; then
    echo "Cert found for domain $i"
  else
    echo "Requesting cert for domain $i..."
    letsencrypt certonly \
      --text --renew-by-default --agree-tos \
      --email=$EMAIL \
      -d $i
  fi
done
