version: '2'
services:
  gitclient.build:
    build: ../gitclient
    image: httpd-gitclient
    entrypoint: ["echo", "This service was just a build job. Exiting."]
  git.build:
    build: ../git
    image: httpd-git
    entrypoint: ["echo", "This service was just a build job. Exiting."]
  githost:
    build: ./githost
    depends_on:
      - git.build
    ports:
      - "80"
  git2:
    image: solsson/httpd@sha256:5bd6cc8c9c3a3dc5d9cd816a602dd7eeb576520343dc9521a594ea13f7ca9d33
    ports:
      - "80"
  httpd:
    build: ../httpd-gitconf
    image: httpd-gitconf
    #entrypoint: git-clones-then-httpd-foreground
