#!/usr/bin/perl
use strict;
use warnings;

if (not $ENV{REQUEST_METHOD}) {
  die('Meant to run as CGI');
}

use CGI::Minimal;
my $cgi = CGI::Minimal->new;
die("truncated, woot?") if ($cgi->truncated);
#if (!$ENV{'ADMIN_REST_ACCESS'}) {
#  die('REST admin not allowed');
#}
print "Content-type: text/plain\n\n";
#die("Request method isn't POST") unless ($ENV{REQUEST_METHOD} eq 'POST');

use ReconfDirGit;
use HttpdControl;

my $control = HttpdControl->new();

$control->reload();

print "Done";
